# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 08:32
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190828_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
